### ISSUE TITLE
question about the negative sets

### ISSUE THREAD

**Issue by Carmelo1997** [BUPT-GAMMA/HeCo#2]
Hi, in your paper, you mentioned the negative sets, but I can't find how to generate the negative samples in your code, could you point it out if possible?
Besides, I'm confused about the computation of the loss in line 34 and line 37 in ./code/module/contrast.py. It seems a bit different from the equation in the paper.

Thank you very much for your paper and the code you shared. Looking forward to your reply :)

**Comment by liun-online** [comment]
Hi, thanks for your attention! 
For the first question, we provide pos.npz to figure out the positive samples. In line 33 and line 36 in./code/module/contrast.py, we give a row normalization to two similarity matrice, so in these two lines, we calculate the denominator of eq.(11) in original paper for each entry. Then, we utlize pos.npz to pick the positive pairs and sum them to finish eq.(11). In this process, negative samples do not expose clearly like positives, but they implicitly participate in the calculation in line 33 and line 36.
For the second question, could you detailedly pointed out what the difference is? Sorry, I cannot get your point.

**Comment by Carmelo1997** [comment]
> Hi, thanks for your attention! For the first question, we provide pos.npz to figure out the positive samples. In line 33 and line 36 in./code/module/contrast.py, we give a row normalization to two similarity matrice, so in these two lines, we calculate the denominator of eq.(11) in original paper for each entry. Then, we utlize pos.npz to pick the positive pairs and sum them to finish eq.(11). In this process, negative samples do not expose clearly like positives, but they implicitly participate in the calculation in line 33 and line 36. For the second question, could you detailedly pointed out what the difference is? Sorry, I cannot get your point.

Thanks for your reply!
I want to confirm that if there are a total of 30 nodes of type X, and for a node i, we sample 5 nodes as positive examples according to the method in the paper, is the negative example of this node i the remaining 25 nodes? So the negative example is not explicitly sampled, right?
If my understanding of negative examples is correct, the second problem I mentioned before is the result of my own misunderstanding, and I figure it out.

**Comment by liun-online** [comment]
yes, you have a correct understanding.
